spring.application.name=security-test
spring.security.user.password=demo@123
spring.security.user.name=admin

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123912738ih2908jkfwhsw897h23ijuhaqw89eftho
spring.app.jwtExpirationMs=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.mel_demo.security_test=DEBUG